import type { Metadata } from 'next'
import './globals.css'
import MuiThemeProvider from '@/theme/Provider'
import Script from 'next/script'
import DefaultLayout from '@/components/layouts/DefaultLayout'


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html suppressHydrationWarning lang="en">
      <Script src="https://unpkg.com/@googlemaps/js-api-loader@1.x/dist/index.min.js" />
      <body suppressContentEditableWarning suppressHydrationWarning>
        <MuiThemeProvider>
          <DefaultLayout>{children}</DefaultLayout>
        </MuiThemeProvider>
      </body>
    </html>
  )
}
